# Generated by Django 3.2.24 on 2024-03-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240302_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskpublic',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
