# Generated by Django 3.2.24 on 2024-03-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240303_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='vence',
            field=models.CharField(max_length=30),
        ),
    ]
