# Generated by Django 3.2.24 on 2024-03-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_vence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskPublic',
        ),
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
