# Generated by Django 3.2.24 on 2024-03-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_etiqueta_etiqueta_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Etiqueta',
            new_name='Tag',
        ),
        migrations.DeleteModel(
            name='Etiqueta_Task',
        ),
        migrations.AddField(
            model_name='tag_task',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag'),
        ),
        migrations.AddField(
            model_name='tag_task',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task'),
        ),
    ]
