# Generated by Django 3.2.24 on 2024-03-18 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20240311_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(to='app.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='vence',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Tag_Task',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
