# Generated by Django 3.2.24 on 2024-03-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240317_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='vence',
            field=models.DateTimeField(null=True),
        ),
    ]
