# Generated by Django 3.2.24 on 2024-03-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_task_vence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='vence',
            field=models.DateTimeField(null=True),
        ),
    ]
